services:
  db:
    image: mariadb:11.5.2
    restart: unless-stopped
    command: --wait-timeout=28800
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "3307:3306"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=kartverket
      - MYSQL_USER=kartverket
      - MYSQL_PASSWORD=passord
    volumes:
      - db:/var/lib/mariadb
  kartverket:
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: Dockerfile
    
volumes:
  db: