// <auto-generated />
using System;
using Kartverket.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kartverket.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241002004346_remove_feilmelding")]
    partial class remove_feilmelding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Kartverket.Models.FeilMeldingsModel", b =>
                {
                    b.Property<int>("geodata_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("geodata_id"));

                    b.Property<int?>("LoginDataUserId")
                        .HasColumnType("int");

                    b.Property<string>("Melding")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StringKoordinaterLag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("geodata_id");

                    b.HasIndex("LoginDataUserId");

                    b.ToTable("geo_data");
                });

            modelBuilder.Entity("Kartverket.Models.LoginDataModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("LoginData");
                });

            modelBuilder.Entity("Kartverket.Models.FeilMeldingsModel", b =>
                {
                    b.HasOne("Kartverket.Models.LoginDataModel", "LoginData")
                        .WithMany()
                        .HasForeignKey("LoginDataUserId");

                    b.Navigation("LoginData");
                });
#pragma warning restore 612, 618
        }
    }
}
